In [1]:
import numpy as np
#import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.decomposition import PCA

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier

In [4]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
from sklearn.metrics import roc_curve, auc

In [5]:
import pandas as pd
titanic_data= pd.read_csv('/kaggle/input/datasets/meftaunnabi/labprac/titanic.csv')

In [6]:
titanic_data.shape

(891, 12)

In [7]:
print(titanic_data.shape)
print(titanic_data.index)
print(titanic_data.columns)
print(len(titanic_data.columns))

(891, 12)
RangeIndex(start=0, stop=891, step=1)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
12

In [8]:
titanic_data.head(n=5)
#print(titanic_data.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,100,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,100,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
titanic_data.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [10]:
#titanic_data.drop("Cabin", axis=1,inplace=True)
titanic_data.drop(["Name","Ticket","Cabin"],axis=1,inplace=True)
titanic_data.head(5)

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0    100      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0    100      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [11]:
titanic_data.info()
#print(titanic_data.info()) #Formated

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB

In [12]:
print(titanic_data['Age'].describe())

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [13]:
#titanic_data['Age'].sort()
s=titanic_data['Age'].sort_values(ascending=True)
print(s)
#print(s.to_string())
#titanic_data['Age']

803    0.42
755    0.67
469    0.75
644    0.75
78     0.83
       ...
859     NaN
863     NaN
868     NaN
878     NaN
888     NaN
Name: Age, Length: 891, dtype: float64

In [14]:
titanic_data.isnull()
#(titanic_data.isnull()).to_string()
#print((titanic_data.isnull()).to_string())

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False
887,False,False,False,False,False,False,False,False,False
888,False,False,False,False,True,False,False,False,False
889,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False

In [15]:
titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
dtype: int64

In [16]:
#titanic_data.Age
titanic_data['Age']
titanic_data['Age'].mean()
age_mean= float(f"{titanic_data['Age'].mean():.2f}")
age_mean

29.7

In [17]:
titanic_data['Age']=titanic_data['Age'].fillna(titanic_data['Age'].mean())
#titanic_data['Age'].fillna(30)
#titanic_data['Age'].fillna(28)
#titanic_data['Age']=titanic_data['Age'].fillna(titanic_data['Age'].median())
#titanic_data['Age']=titanic_data['Age'].fillna(titanic_data['Age'].mode()[0])
#titanic_data.info()
titanic_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       2
dtype: int64

In [18]:
titanic_data['Embarked'].mode()
titanic_data['Embarked'].mode()[0]

'S'

In [19]:
titanic_data['Embarked']=titanic_data['Embarked'].fillna(titanic_data['Embarked'].mode()[0])

titanic_data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [20]:
titanic_data.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0    100      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0    100      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [21]:
titanic_data['Sex'].value_counts()
#titanic_data['Sex'].value_counts().tolist()

Sex
male      577
female    314
Name: count, dtype: int64

In [22]:
print(titanic_data['Sex'].unique().tolist())
print(titanic_data['Sex'].value_counts().tolist())

['male', 'female']
[577, 314]

In [23]:
titanic_data['Embarked'].value_counts()
#titanic_data['Sex'].value_counts().tolist()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [24]:
#print(type(titanic_data))
#print(type(titanic_data['Embarked']))
print(titanic_data['Embarked'].unique().tolist())
print(titanic_data['Sex'].value_counts().tolist())

['S', 'C', 'Q']
[577, 314]